version: "3.7"
services:
  db:
    container_name: king_roger
    restart: always
    image: king_roger
    build:
      context: ./postgres

    environment:
      POSTGRES_USER: RobotBoy
      POSTGRES_PASSWORD: RobotBoy  # To be moved to environment file
      POSTGRES_DATABASE: KingRoger
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - king_roger-facade
  graphql:
    container_name: facade
    restart: always
    image: facade
    build:
      context: ../src/AppiSimo.Server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://RobotBoy:RobotBoy@db:5432/KingRoger # To be moved to environment file
      PORT: 5000
    expose:
      - 6000
    ports:
      - 6000:5000
    links:
      - db
    networks:
      - king_roger-facade
networks:
  king_roger-facade: